### ISSUE TITLE
Sourcing will be disregarded

### ISSUE THREAD

**Issue by minhtriet** [alexanderrichard/queueing-tool#1]
When you have to source a file, the tool will disregard your setting and run with system's default, which can lead to failure

**Comment by alexanderrichard** [comment]
You can source any file you want. However, you have to source it within the block you need it. E.g.:

     #block(name=my-block, memory=2000, threads=1, gpus=0)
         source my_file.sh
         # do things...`

**Comment by minhtriet** [comment]
Great! Perhaps adding this example to the readme.md will benefit other users.
